### ISSUE TITLE
Feature request: Try CSS subgrids in cards

### ISSUE THREAD

**Issue by mejiaj** [mejiaj/mejiaj#100]
### Is your feature request related to a problem? Please describe.

The inner card elements don't align.

### Describe the solution you'd like

Explore subgrid to avoid explicitly setting `min-height` to child elements.

### Describe alternatives you've considered

n/a

### Additional context

**Example**
```css
.card-rows {
  grid-template-columns: repeat(3, 1fr);
}

.cards {
  grid-template-colums: subgrid;
}
```
